name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: "24"
          distribution: "temurin"
          cache: "maven"
      - name: Build and Check Format with Spotless
        run: mvn compile spotless:check
      - name: Test
        run: mvn test
